# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-28 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retrain_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newclass',
            name='thumbnail_subects',
        ),
    ]
