# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-30 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrain_model', '0004_remove_newclass_new_training_set_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='newclass',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
