# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-11 18:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('1080LINE', '1080 Line'), ('1400RIPPLE', '1400 Ripple'), ('AIRCOMPRESSOR50HZ', 'Air Compressor 50Hz'), ('BLIP', 'Blip'), ('CHIRP', 'Chirp'), ('EXTREMELYLOUD', 'Extremely Loud'), ('HELIX', 'Helix'), ('KOIFISH', 'Koi Fish'), ('LIGHTMODULATION', 'Light Modulation'), ('LOWFREQUENCYBURST', 'Low Frequency Burst'), ('LOWFREQUENCYLINE', 'Low Frequency Line'), ('NOGLITCH', 'No Glitch'), ('NONEOFTHEABOVE', 'None of the Above'), ('PAIREDDOVES', 'Paired Doves'), ('POWERLINE60HZ', 'Power Line 60Hz'), ('REPEATINGBLIPS', 'Repeating  Blips'), ('SCATTEREDLIGHT', 'Scattered Light'), ('SCRATCHY', 'Scratchy'), ('TOMTE', 'Tomte'), ('VIOLINMODEHARMONIC', 'Violin Mode Harmonic'), ('WANDERINGLINE', 'Wandering Line'), ('WHISTLE', 'Whistle')], max_length=30)),
                ('gravityspy_id', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
