# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-11 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='user',
            field=models.CharField(max_length=40),
        ),
    ]
