# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-11 22:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_auto_20180711_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
