# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-12 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_auto_20180711_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='agreed',
            field=models.CharField(choices=[('AGREE', 'Agree'), ('DISAGREE', 'Disagree')], default='AGREE', max_length=8),
            preserve_default=False,
        ),
    ]
